version: 2
updates:
  - package-ecosystem: "pip"
    directories:
     - "/"
     - "/tests"
    schedule:
      interval: "cron"
      cronjob: "45 14 * * *"
    groups:
      python-dependencies:
        patterns:
          - "*"
